### ISSUE TITLE
CloudRobot.getCleaningSessions() results in KeyError: cleaningSession

### ISSUE THREAD

**Issue by Phype** [Phype/purei9_unofficial#15]
See https://github.com/Ekman/home-assistant-pure-i9/issues/10

**Comment by Ekman** [comment]
Using Postman I found some cleaning sessions looking like this:

```json
[
    {
        "id": "obfuscated",
        "sessionId": 1337,
        "timeStamp": "2021-11-20T14:14:39",
        "cleanedArea": 18.87,
        "totalLifetimeCleanedArea": 10318.514
    }
]
```

**Comment by Phype** [comment]
I've uploaded version 0.0.9 which attempts to fix this by changing cleaningsession.starttime to cleaningsession.endtime. The endtime is available in every item, the start time is not. Also this means the cleaningDuration will not be available in all items. Please check it out if it works for you since i couldn't test it on my account.

**Comment by Ekman** [comment]
Thanks! I'll test and report back.

**Comment by Phype** [comment]
I'll assume this works as intended and close it for now.
