### ISSUE TITLE
Support for new API

### ISSUE THREAD

**Issue by Phype** [Phype/purei9_unofficial#22]
Given that the Wellbeeing app is going to be deprecated at some point, we'll probably need to move to the API used by the newest app. See #21.

**Comment by louisjennings** [comment]
I have created a pull request (#23) adding this functionality. The API calls were determined by MitMing the Android app.

**Comment by Phype** [comment]
Thanks! I merged the PR and added some tests. Also renamed to to v3, because i think this is easier and the API will probably break at some point anyway.
