### ISSUE TITLE
Add possibility to clean a certain area

### ISSUE THREAD

**Issue by fastender** [Phype/purei9_unofficial#7]
Very helpful your app. I use the cloud version of you. 

Is there any possibility to add more commands like pause or clean certain area?

**Comment by Phype** [comment]
Pausing should be possible using the pause command, however not that this is implemented in the robot using a toggle, so running "start" and "pause" actually does the same thing - it toggles between pause and resume.

Aadding a command to clean certain areas is possible, but i haven't looked into how the API works. Maybe i'll add this in the future.

**Comment by Phype** [comment]
PS: If you have other request for specific functionality, leave them here or in another issue, i'll see what i can do.

**Comment by fastender** [comment]
Right. Pause works.

Thank you.

If the suction speed and the map function I mentioned would be implented, it would be really great. Thank you very much.

https://community.home-assistant.io/t/integrating-eectrolux-pure-i9-robotic-vacuum/78648/19?u=fastender
